add a protection

diff --git a/.github/workflows/new-release.yml b/.github/workflows/new-release.yml
--- a/.github/workflows/new-release.yml
+++ b/.github/workflows/new-release.yml
@@ -3,6 +3,9 @@ name: Create Release
 on:
   workflow_dispatch:
     inputs:
+      are-you-sure:
+        description: 'Are you sure you want to cut a release? Only "YES!!!" will be accepted'
+        required: true
       version:
         description: 'Version number (leave empty to auto-increment)'
         required: false
@@ -30,7 +33,12 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
-          FLAGS=""
+          if [[ "${{ inputs.are-you-sure }}" != "YES!!!" ]]; then
+            echo "Error: You must enter 'YES!!!' to confirm."
+            exit 1
+          fi
+
+          FLAGS="-are-you-sure='${{ inputs.are-you-sure }}'"
 
           # Add version flag if provided
           if [ -n "${{ inputs.version }}" ]; then
